const {
  REACT_APP_TRONSCAN_ADDRESS = "",
  REACT_APP_EXPLORER_ADDRESS = "",
  REACT_APP_RISE_CONTRACT_ADDRESS = "",
  REACT_APP_CASH_CONTRACT_ADDRESS = "",
  REACT_APP_TRON_HOST = "",
  REACT_APP_TRON_FULL_HOST = "",
  REACT_APP_TRON_FULL_NODES = "",
  REACT_APP_TRON_SOLIDITY_NODES = "",
  REACT_APP_TRON_PRIVATE_KEY = "",
} = process.env;

const TOKEN_DECIMALS = 100000000;

export {
  REACT_APP_TRONSCAN_ADDRESS as TRONSCAN_ADDRESS,
  REACT_APP_EXPLORER_ADDRESS as EXPLORER_ADDRESS,
  REACT_APP_RISE_CONTRACT_ADDRESS as RISE_CONTRACT_ADDRESS,
  REACT_APP_CASH_CONTRACT_ADDRESS as CASH_CONTRACT_ADDRESS,
  REACT_APP_TRON_HOST as TRON_HOST,
  REACT_APP_TRON_FULL_HOST as TRON_FULL_HOST,
  REACT_APP_TRON_FULL_NODES as TRON_FULL_NODES,
  REACT_APP_TRON_SOLIDITY_NODES as TRON_SOLIDITY_NODES,
  REACT_APP_TRON_PRIVATE_KEY as TRON_PRIVATE_KEY,
  TOKEN_DECIMALS,
};
